[project]
name = "fish-segmentation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
{ name = "Guillermo Oliva", email = "gllrmoliva42@gmail.com" }
]
requires-python = "==3.12.*"
dependencies = [
    "einops>=0.8.2",
    "flash-attn-3>=3.0.0",
    "gdown>=6.1.0",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.3",
    "matplotlib>=3.11.1",
    "ninja>=1.13.0",
    "pandas>=3.0.5",
    "pathlib>=1.0.1",
    "python-dotenv>=1.2.3",
    "sam3[dev,notebooks,train]",
    "seaborn>=0.13.2",
    "setuptools<82",
    "torch==2.10.0",
    "torchvision>=0.25.0",
    "triton>=3.6.0 ; sys_platform != 'win32'",
]

[project.scripts]
fish-segmentation = "fish_segmentation:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
sam3 = { workspace = true, editable = true }

[tool.uv.workspace]
members = [
    "sam3_src",
]

# esto es para confiar en pytorch
[tool.uv]
index-strategy = "unsafe-best-match"
environments = [
    "sys_platform == 'linux'",
]
